### PR TITLE
Add Chebyshev T and U transforms

### PR DESCRIPTION
**Pull request by dlfivefifty**
Resolves

https://github.com/JuliaApproximation/ApproxFun.jl/issues/433

Also has first example for https://github.com/MikaelSlevinsky/FastTransforms.jl/issues/47

### CODE REVIEW

**Comment by MikaelSlevinsky** [comment]
The `applyTN*` (and similar) functions were used for the cjt.

**Comment by dlfivefifty** [comment]
Yes I'm updating them now to use `chebyshevtransform`

**Comment by dlfivefifty** [comment]
Checks pass! @MikaelSlevinsky Are you happy for me to merge?

**Comment by dlfivefifty** [comment]
Ooh, and nightly is fixed too 🤩

**Comment by MikaelSlevinsky** [comment]
Yep, sounds good!

**Comment by dlfivefifty** [comment]
I'll probably tag a new minor release, now that 0.7 tests are passing in Travis

**Pull request merged**
